name: eja_yuk
description: Aplikasi Pembelajaran Mengeja untuk Anak Usia Dini
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Database lokal — simpan skor, status stage, sesi login
  shared_preferences: ^2.2.2
  # State management ringan (ChangeNotifier)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Generate launcher icon otomatis
  flutter_launcher_icons: ^0.13.1

# ---- Konfigurasi App Icon ----
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FF8C00"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/